version: '3.3'

services:
  front-end:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      # - ./proxy/log:/var/log/nginx/ #enable if you want to see logs
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./front-end:/front-end
      - ./proxy/env/front-end-env.js:/front-end/env.js
    networks:
        - test
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: simple_http
    # ports:
    #   - 8081:80
    networks:
        - test
networks:
  test: